paths:
  model_weights_directory: /grphome/fslg_census/nobackup/archive/machine_learning_models/classification_models/general_weights
  transfer_learn_weights_file:
  metrics_dir_path: /grphome/fslg_census/nobackup/archive/machine_learning_models/classification_models/metrics
  image_paths_and_labels: /grphome/fslg_census/nobackup/archive/machine_learning_models/classification_models/branches/main/RLL_classifiers_pytorch/tests/resources/labels_for_gender_snippets.tsv

dataset_params:
  dataset_name: test_resources_gender
  inference: False
  batch_size: 2
  hold_images_in_RAM: True
  random_split: True
  random_state:
  stratified_split: True
  test_size: .1

model_architecture_parameters:
  model_name: resnet50
  output_classes: 2

model_hyper_parameters:
  learning_rate: .001
  epochs: 20
  optimizer_name: adam
  weight_decay: 0
  device: cpu

other_parameters:
  early_stopping: False
  track_val_every_n_epochs: 20